spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/intercorp_assessment
    username: postgres
  application:
    name: eureka-client

eureka:
  instance:
    hostname: ${DOMAIN_NAME:localhost}
    nonSecurePort: 80
  client:
    proxy-password: ${USER_PASSWORD:password}



---

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:5000}/eureka/
